name: Build Gatsby site on Main

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Gatsby site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Clean npm Cache
        run: npm cache clean --force

      - name: Delete package-lock.json
        run: rm package-lock.json

      - name: Update Dependencies
        run: npm install

      - name: Check for Outdated Dependencies
        run: npm outdated

      - name: Build
        run: npm run build  # Adjust this command if needed

      - name: Deploy
        run: npm run deploy:ci        