# name: Deploy Gatsby site to Pages

# on:
#   push:
#     branches:
#       - main

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write

# # Allow one concurrent deployment
# concurrency:
#   group: "pages"
#   cancel-in-progress: true

# # Default to bash
# defaults:
#   run:
#     shell: bash

# jobs:
#   # Build job
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2
      
#       - name: Setup Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: '20'  # Adjust the Node.js version as needed
      
#       - name: Clean npm Cache
#         run: npm cache clean --force
      
#       - name: Delete package-lock.json
#         run: rm package-lock.json
      
#       - name: Update Dependencies
#         run: npm install
      
#       - name: Clean and Rebuild
#         run: |
#           npm run clean
#           npm run build  # Adjust this command if needed
      
#       - name: Upload artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: gatsby-build  # Make sure this matches the artifact name
#           path: ./public

#   # Deployment job
#   deploy:
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v2
#         with:
#           token: ${{ secrets.portfoliogatsby }}  # Use the GITHUB_TOKEN for deployment


# # name: Deploy Gatsby site to Pages

# # on:
# #   push:
# #     branches:
# #       - main

# #   # Allows you to run this workflow manually from the Actions tab
# #   workflow_dispatch:

# # # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# # permissions:
# #   contents: read
# #   pages: write
# #   id-token: write

# # # Allow one concurrent deployment
# # concurrency:
# #   group: "pages"
# #   cancel-in-progress: true

# # # Default to bash
# # defaults:
# #   run:
# #     shell: bash

# # jobs:
# #   # Build job
# #   build:
# #     runs-on: ubuntu-latest
# #     steps:
# #       - name: Checkout Code
# #         uses: actions/checkout@v2
      
# #       - name: Install Node.js
# #         uses: actions/setup-node@v1
# #         with:
# #           node-version: '20' 
      
# #       - name: Clean npm Cache
# #         run: npm cache clean --force
      
# #       - name: Delete package-lock.json
# #         run: rm package-lock.json
      
# #       - name: Update Dependencies
# #         run: npm install
      
# #       - name: Build
# #         run: npm run build  # Adjust this command if needed
      
# #       - name: Upload artifact
# #         uses: actions/upload-artifact@v2
# #         with:
# #           name: gatsby-build
# #           path: ./public

# #   # Deployment job
# #   deploy:
# #     environment:
# #       name: github-pages
# #       url: ${{ steps.deployment.outputs.page_url }}
# #     runs-on: ubuntu-latest
# #     needs: build
# #     steps:
# #       - name: Deploy to GitHub Pages
# #         id: deployment
# #         uses: actions/deploy-pages@v2
# #         with:
# #           deploy_key: ${{ secrets.portfoliogatsby }}  # Use the GITHUB_TOKEN for deployment
# #           artifact_path: ./public



# # name: Build and Deploy Gatsby Site

# # on:
# #   push:
# #     branches:
# #       - main

# # jobs:
# #   build-and-deploy:
# #     name: build
# #     runs-on: ubuntu-latest

# #     steps:
# #       - name: Checkout Code
# #         uses: actions/checkout@v2

# #       - name: Setup Node.js
# #         uses: actions/setup-node@v2
# #         with:
# #           node-version: '14'  # Adjust the Node.js version as needed

# #       - name: Clean npm Cache
# #         run: npm cache clean --force

# #       - name: Delete package-lock.json
# #         run: rm package-lock.json

# #       - name: Update Dependencies
# #         run: npm install

# #       - name: Check for Outdated Dependencies
# #         run: npm outdated

# #       - name: Build
# #         run: npm run build  # Adjust this command if needed

# #   # Deployment job
# #   deploy:
# #     environment:
# #       name: github-pages
# #       url: ${{ steps.deployment.outputs.page_url }}
# #     runs-on: ubuntu-latest
# #     needs: build
# #     steps:
# #       - name: Deploy to GitHub Pages
# #         id: deployment
# #         uses: actions/deploy-pages@v1










# # name: Build and Deploy

# # on:
# #   push:
# #     branches:
# #       - main

# # jobs:
# #   build-and-deploy:
# #     name: Build and deploy Gatsby site
# #     runs-on: ubuntu-latest
# #     steps:
# #       - name: Checkout Code
# #         uses: actions/checkout@v2.3.1

# #       - name: Install Node.js
# #         uses: actions/setup-node@v1
# #         with:
# #           node-version: '20'

# #       - name: Install Project Dependencies
# #         run: npm ci

# #       - name: Install Gatsby CLI
# #         run: npm install -g gatsby-cli@2.12.34

# #       - name: Build
# #         run: gatsby build

# #       - name: Verify build
# #         run: ls -la public

# #       - name: Commit and Push
# #         uses: stefanzweifel/git-auto-commit-action@v4
# #         with:
# #           commit_message: 'Automated deployment' # Customize the commit message
# #           commit_options: '--author "JAlcocerT <jalcocert@fossengineer.com>"' # Customize the author info
# #           repository: ${{ github.repository }}
# #           branch: gh-pages # Replace with the branch you want to deploy to
# #           files: 'public/*'
# #           token: ${{ secrets.portfoliogatsby }}



# # name: Build Gatsby site on Main

# # on:
# #   push:
# #     branches:
# #       - main

# # jobs:
# #   build-and-deploy:
# #     name: Build and Deploy Gatsby site
# #     runs-on: ubuntu-latest

# #     steps:
# #       - name: Checkout Code
# #         uses: actions/checkout@v2

# #       - name: Setup Node.js
# #         uses: actions/setup-node@v2
# #         with:
# #           node-version: '20'

# #       - name: Clean npm Cache
# #         run: npm cache clean --force

# #       - name: Delete package-lock.json
# #         run: rm package-lock.json

# #       - name: Update Dependencies
# #         run: npm install

# #       - name: Check for Outdated Dependencies
# #         run: npm outdated

# #       - name: Build
# #         run: npm run build  # Adjust this command if needed

# #       - name: Deploy
# #         run: npm run deploy:ci        