name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install Project Dependencies
        run: npm ci

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@2.12.34

      - name: Build
        run: gatsby build

      - name: Verify build
        run: ls -la public

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automated deployment' # Customize the commit message
          commit_options: '--author "JAlcocerT <jalcocert@fossengineer.com>"' # Customize the author info
          repository: ${{ github.repository }}
          branch: gh-pages # Replace with the branch you want to deploy to
          files: 'public/*'
          token: ${{ secrets.portfoliogatsby }}



# name: Build Gatsby site on Main

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     name: Build and Deploy Gatsby site
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '20'

#       - name: Clean npm Cache
#         run: npm cache clean --force

#       - name: Delete package-lock.json
#         run: rm package-lock.json

#       - name: Update Dependencies
#         run: npm install

#       - name: Check for Outdated Dependencies
#         run: npm outdated

#       - name: Build
#         run: npm run build  # Adjust this command if needed

#       - name: Deploy
#         run: npm run deploy:ci        